let state={profile:"new",template:"modern",items:[],sig:null};let seq=0;
const profiles={purva:{name:"Purva",email:"",phone:"",address:"",bankName:"",bankAcc:"",bankIfsc:"",upiId:""},harsh:{name:"Harsh",email:"",phone:"",address:"",bankName:"",bankAcc:"",bankIfsc:"",upiId:""}};
const templates=[["modern","Modern"],["classic","Classic"],["minimal","Minimal"],["bold","Bold"]];
function el(id){return document.getElementById(id)} function v(id){return el(id)?.value||""}
function esc(s){return String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function money(n){return "₹"+(Number(n)||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}
function dateFmt(d){if(!d)return"";let x=new Date(d+"T00:00:00");return isNaN(x)?"":x.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}
function words(n){n=Math.round(n);if(!n)return"Zero";let o=["","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen","Seventeen","Eighteen","Nineteen"],t=["","","Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"];function two(x){return x<20?o[x]:t[Math.floor(x/10)]+(x%10?" "+o[x%10]:"")}function three(x){return x<100?two(x):o[Math.floor(x/100)]+" Hundred"+(x%100?" "+two(x%100):"")}let r="",c=Math.floor(n/1e7);n%=1e7;let l=Math.floor(n/1e5);n%=1e5;let th=Math.floor(n/1e3);n%=1e3;if(c)r+=three(c)+" Crore ";if(l)r+=three(l)+" Lakh ";if(th)r+=three(th)+" Thousand ";if(n)r+=three(n);return r.trim()}
function newItem(){return{id:++seq,name:"",desc:"",qty:1,rate:0,subs:[]}}
function newSub(){return{id:++seq,name:"",desc:"",qty:1,rate:0}}
function startInvoice(profile){state.profile=profile;state.template="modern";state.items=[newItem()];state.sig=null;el("dashboard").style.display="none";el("editor").style.display="block";let p=profiles[profile]||{};["name","email","phone","address","bankName","bankAcc","bankIfsc","upiId"].forEach(k=>{let id={name:"bizName",email:"bizEmail",phone:"bizPhone",address:"bizAddress",bankName:"bankName",bankAcc:"bankAcc",bankIfsc:"bankIfsc",upiId:"upiId"}[k];el(id).value=p[k]||""});el("invDate").value=new Date().toISOString().slice(0,10);renderTemplates();renderItems();render()}
function goHome(){el("editor").style.display="none";el("dashboard").style.display="block"}
function renderTemplates(){el("templateBar").innerHTML=templates.map(t=>`<button class="chip ${state.template==t[0]?"active":""}" onclick="chooseTemplate('${t[0]}')">${t[1]}</button>`).join("")}
function chooseTemplate(t){state.template=t;renderTemplates();render()}
function addItem(){state.items.push(newItem());renderItems();render()}
function addSub(i){state.items[i].subs.push(newSub());renderItems();render()}
function removeItem(i){if(state.items.length>1)state.items.splice(i,1);renderItems();render()}
function removeSub(i,s){state.items[i].subs.splice(s,1);renderItems();render()}
function field(i,key,value,sub){let a=sub?state.items[i].subs[sub]:state.items[i];a[key]=(key=="qty"||key=="rate")?Number(value)||0:value;render()}
function renderItems(){el("itemsList").innerHTML=state.items.map((x,i)=>`<div class="item"><div class="head"><span>Item ${i+1}</span><button onclick="removeItem(${i})">Remove</button></div>
<div class="field"><label>Product / service</label><input value="${esc(x.name)}" oninput="field(${i},'name',this.value)"></div>
<div class="field"><label>Description</label><input value="${esc(x.desc)}" oninput="field(${i},'desc',this.value)"></div>
<div class="row3"><div class="field"><label>Qty</label><input type="number" value="${x.qty}" oninput="field(${i},'qty',this.value)"></div><div class="field"><label>Rate ₹</label><input type="number" value="${x.rate}" oninput="field(${i},'rate',this.value)"></div><div class="field"><label>Amount</label><input disabled value="${money(x.qty*x.rate)}"></div></div>
<div class="subitems">${x.subs.map((s,j)=>`<div class="sub"><div class="subhead"><span>Sub-item ${j+1}</span><button onclick="removeSub(${i},${j})">Remove</button></div><div class="field"><label>Name</label><input value="${esc(s.name)}" oninput="field(${i},'name',this.value,${j})"></div><div class="field"><label>Description</label><input value="${esc(s.desc)}" oninput="field(${i},'desc',this.value,${j})"></div><div class="row3"><div class="field"><label>Qty</label><input type="number" value="${s.qty}" oninput="field(${i},'qty',this.value,${j})"></div><div class="field"><label>Rate ₹</label><input type="number" value="${s.rate}" oninput="field(${i},'rate',this.value,${j})"></div><div class="field"><label>Amount</label><input disabled value="${money(s.qty*s.rate)}"></div></div></div>`).join("")}</div>
<button class="add" onclick="addSub(${i})">+ Add sub-item</button></div>`).join("")}
function totalItem(x){return x.qty*x.rate+x.subs.reduce((a,s)=>a+s.qty*s.rate,0)}
function render(){let items=state.items,sub=items.reduce((a,x)=>a+totalItem(x),0),dv=Number(v("discVal"))||0,discount=v("discType")=="percent"?sub*dv/100:dv,coupon=Number(v("couponAmt"))||0,base=Math.max(0,sub-discount-coupon),gst=base*(Number(v("gstPct"))||0)/100,cgst=base*(Number(v("cgstPct"))||0)/100,sgst=base*(Number(v("sgstPct"))||0)/100,extra=Number(v("extraAmt"))||0,total=base+gst+cgst+sgst+extra;
let rows=[];items.forEach((x,i)=>{rows.push(`<tr><td>${i+1}</td><td><b>${esc(x.name)||"—"}</b>${x.desc?`<div class="desc">${esc(x.desc)}</div>`:""}</td><td>${x.qty}</td><td>${money(x.rate)}</td><td>${money(x.qty*x.rate)}</td></tr>`);x.subs.forEach(s=>rows.push(`<tr class="subrow"><td></td><td>↳ ${esc(s.name)||"—"}${s.desc?`<div class="desc">${esc(s.desc)}</div>`:""}</td><td>${s.qty}</td><td>${money(s.rate)}</td><td>${money(s.qty*s.rate)}</td></tr>`))});
let data={biz:{name:v("bizName")||"Your Name",email:v("bizEmail"),phone:v("bizPhone"),address:v("bizAddress")},cli:{name:v("cliName")||"Client Name",email:v("cliEmail"),phone:v("cliPhone"),address:v("cliAddress")},title:v("invTitle")||"INVOICE",no:v("invNo"),date:v("invDate"),due:v("invDue"),rows:rows.join(""),subtotal:sub,discount,coupon,gst,cgst,sgst,extra,extraLabel:v("extraLabel"),total,words:words(total),bankName:v("bankName"),bankAcc:v("bankAcc"),bankIfsc:v("bankIfsc"),upi:v("upiId"),thanks:v("thankYou"),terms:v("terms"),sig:state.sig,typeSig:v("sigType")};
renderTemplate(data)}
async function renderTemplate(d){let html=await fetch("template-"+state.template+".html").then(r=>r.text()).catch(()=>"<div>Template not found</div>");let css=html.match(/<style[^>]*>([\\s\\S]*?)<\\/style>/i)?.[1]||"";let body=html.replace(/<style[\\s\\S]*?<\\/style>/i,"").replace(/<script[\\s\\S]*?<\\/script>/gi,"");let data=JSON.stringify(d).replace(/</g,"\\u003c");let out=body.replace("<!--INVOICE-->",buildInvoice(d));el("invoicePreview").innerHTML=`<style>${css}</style>${out}`;if(state.template==="bold")el("invoicePreview").classList.add("bold")}
function buildInvoice(d){let sig=d.sig?`<img src="${d.sig}">`:d.typeSig?`<div class="typed">${esc(d.typeSig)}</div>`:"";return `<div class="invoice-head"><div><h1>${esc(d.biz.name)}</h1><p>${esc(d.biz.email)}<br>${esc(d.biz.phone)}<br>${esc(d.biz.address).replace(/\n/g,"<br>")}</p></div><div class="title"><h2>${esc(d.title)}</h2><small>${d.no?"# "+esc(d.no):""}</small></div></div><hr><div class="parties"><div><b>BILLED TO</b><strong>${esc(d.cli.name)}</strong><span>${esc(d.cli.email)}<br>${esc(d.cli.phone)}<br>${esc(d.cli.address).replace(/\n/g,"<br>")}</span></div><div><b>INVOICE DETAILS</b><span>${d.date?"Date: "+dateFmt(d.date):""}<br>${d.due?"Due: "+dateFmt(d.due):""}</span></div></div><table><thead><tr><th>Sr</th><th>Item</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${d.rows}</tbody></table><div class="bottom"><div>${d.terms?`<b>NOTES</b><p>${esc(d.terms).replace(/\n/g,"<br>")}</p>`:""}</div><div class="totals"><p>Subtotal <span>${money(d.subtotal)}</span></p>${d.discount?`<p>Discount <span>-${money(d.discount)}</span></p>`:""}${d.coupon?`<p>Coupon <span>-${money(d.coupon)}</span></p>`:""}${d.gst?`<p>GST <span>${money(d.gst)}</span></p>`:""}${d.cgst?`<p>CGST <span>${money(d.cgst)}</span></p>`:""}${d.sgst?`<p>SGST <span>${money(d.sgst)}</span></p>`:""}${d.extra?`<p>${esc(d.extraLabel||"Extra")} <span>${money(d.extra)}</span></p>`:""}<h3>Total <span>${money(d.total)}</span></h3><i>Rupees ${d.words} Only</i></div></div><footer><div>${d.bankName||d.bankAcc||d.bankIfsc||d.upi?`<b>PAYMENT DETAILS</b><p>${d.bankName?"Bank: "+esc(d.bankName)+"<br>":""}${d.bankAcc?"A/c No: "+esc(d.bankAcc)+"<br>":""}${d.bankIfsc?"IFSC: "+esc(d.bankIfsc)+"<br>":""}${d.upi?"UPI: "+esc(d.upi):""}</p>`:""}<strong>${esc(d.thanks)}</strong></div><div class="sig">${sig}<hr><small>Authorised signatory</small></div></footer></div>`}
function mobileView(x){el("layout").className="layout "+(x=="form"?"formOnly":"previewOnly");el("editBtn").classList.toggle("active",x=="form");el("previewBtn").classList.toggle("active",x=="preview")}
function clearSig(){let c=el("sigPad"),x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);state.sig=null;render()}
let c=el("sigPad"),ctx=c.getContext("2d"),draw=false;c.addEventListener("pointerdown",e=>{draw=true;ctx.beginPath();let r=c.getBoundingClientRect();ctx.moveTo((e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height)});c.addEventListener("pointermove",e=>{if(!draw)return;let r=c.getBoundingClientRect();ctx.lineTo((e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height);ctx.stroke()});window.addEventListener("pointerup",()=>{if(draw){draw=false;state.sig=c.toDataURL("image/png");render()}});
document.getElementById("formPanel").addEventListener("input",e=>{if(!e.target.closest("#itemsList"))render()});document.getElementById("formPanel").addEventListener("change",render);
document.getElementById("downloadBtn").onclick=async()=>{let b=el("downloadBtn");b.disabled=true;b.textContent="Preparing PDF…";try{let canvas=await html2canvas(el("invoicePreview"),{scale:2,backgroundColor:"#fff",useCORS:true}),{jsPDF}=window.jspdf,pdf=new jsPDF("p","pt","a4"),w=pdf.internal.pageSize.getWidth(),h=pdf.internal.pageSize.getHeight(),ih=canvas.height*w/canvas.width;let y=0,ph=Math.floor(canvas.width*h/w);while(y<canvas.height){let sh=Math.min(ph,canvas.height-y),sc=document.createElement("canvas");sc.width=canvas.width;sc.height=sh;sc.getContext("2d").drawImage(canvas,0,y,canvas.width,sh,0,0,canvas.width,sh);if(y)pdf.addPage();pdf.addImage(sc.toDataURL("image/png"),"PNG",0,0,w,sh*w/canvas.width);y+=sh}pdf.save((v("invNo")?"invoice-"+v("invNo"):"invoice")+".pdf")}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent="⬇ Download PDF"}};
